# Generated by Django 3.1.7 on 2021-04-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [xa
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=4, unique=True)),
                ('Name', models.CharField(max_length=255)),
                ('Qty', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
